const stateLabels={RISK_ON:"Risk on",RISK_OFF:"Risk off",DEFENSIVE:"Defensiv",NEUTRAL:"Neutral",OVERHEATED:"Överhettad",RE_ENTRY:"Återinträde",UNAVAILABLE:"Ej tillgänglig"};
const tdaFeatureLabels={a_h0_finite_count:"Gren A · H₀ ändliga komponenter",a_h0_max_persistence:"Gren A · H₀ maximal persistens",a_h0_total_persistence:"Gren A · H₀ total persistens",a_h0_persistence_entropy:"Gren A · H₀ persistensentropi",a_h0_bottleneck_previous:"Gren A · H₀ förändring mot föregående dag",a_h1_finite_count:"Gren A · H₁ ändliga slingor",a_h1_max_persistence:"Gren A · H₁ maximal persistens",a_h1_total_persistence:"Gren A · H₁ total persistens",a_h1_persistence_entropy:"Gren A · H₁ persistensentropi",a_h1_bottleneck_previous:"Gren A · H₁ förändring mot föregående dag",b_h0_finite_count:"Gren B · H₀ ändliga komponenter",b_h0_max_persistence:"Gren B · H₀ maximal persistens",b_h0_total_persistence:"Gren B · H₀ total persistens",b_h0_persistence_entropy:"Gren B · H₀ persistensentropi",b_h0_bottleneck_previous:"Gren B · H₀ förändring mot föregående dag",b_h1_finite_count:"Gren B · H₁ ändliga slingor",b_h1_max_persistence:"Gren B · H₁ maximal persistens",b_h1_total_persistence:"Gren B · H₁ total persistens",b_h1_persistence_entropy:"Gren B · H₁ persistensentropi",b_h1_bottleneck_previous:"Gren B · H₁ förändring mot föregående dag"};
const domainIcons={sweden:"SE",usa:"US",global:"G20"};
const domainData={};
async function api(path){let target;let select=data=>data;if(path==="/api/v1/domains")target="data/domains.json";else if(path==="/api/v1/alerts")target="data/alerts.json";else if(path==="/api/v1/quality/issues")target="data/quality/issues.json";else if(path==="/api/v1/tda/latest")target="data/tda/latest.json";else if(path==="/api/v1/tda/universe")target="data/tda/universe.json";else if(path.startsWith("/api/v1/synthesis/preview")){target="data/profiles.json";const profile=new URL(path,"https://makrolage.invalid").searchParams.get("profile")||"global-fund-heavy";select=data=>data[profile]}else{let match=path.match(/^\/api\/v1\/domains\/([^/]+)\/signals(?:\?limit=(\d+))?$/);if(match){target=`data/signals/${encodeURIComponent(match[1])}.json`;const limit=Number(match[2]||5000);select=data=>data.slice(0,limit)}else{match=path.match(/^\/api\/v1\/signals\/([^/]+)\/audit$/);if(match)target=`data/audits/${encodeURIComponent(match[1])}.json`}}if(!target)throw new Error(`Okänd statisk resurs: ${path}`);const response=await fetch(new URL(target,document.baseURI),{cache:"no-cache"});if(!response.ok)throw new Error(`Snapshot saknas (${response.status})`);return select(await response.json())}
function formatDate(value){if(!value)return"—";return new Intl.DateTimeFormat("sv-SE",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Stockholm"}).format(new Date(value))}
function number(value,digits=2){return value==null?"—":new Intl.NumberFormat("sv-SE",{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(value)}
function esc(value){return String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c])}
function showView(name){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===`view-${name}`));document.querySelectorAll(".nav-link").forEach(b=>b.classList.toggle("active",b.dataset.view===name));location.hash=name}
document.querySelectorAll(".nav-link").forEach(button=>button.addEventListener("click",()=>showView(button.dataset.view)));
document.getElementById("alert-button").addEventListener("click",()=>showView("quality"));
document.getElementById("profile-select").addEventListener("change",async event=>{const prepared=await api(`/api/v1/synthesis/preview?profile=${encodeURIComponent(event.target.value)}`);renderSynthesis(prepared.latest);renderHistory(prepared.signals.slice(0,24))});

function domainCard(item){const s=item.latest;if(!s)return"";const delta=s.score_change==null?"Första beräkningen":`${s.score_change>=0?"+":""}${number(s.score_change)} sedan föregående`;
 return `<article class="domain-card"><div class="card-top"><div><span class="state ${esc(s.state)}">${stateLabels[s.state]||esc(s.state)}</span><h3>${esc(item.label)}</h3></div><span class="domain-icon">${domainIcons[item.id]}</span></div><div class="card-score"><strong>${number(s.score)}</strong><span>${delta}</span></div><div class="mini-bar"><i style="width:${Math.min(50,Math.abs(s.score||0)/2*50)}%;${s.score<0?'right:50%;left:auto;background:var(--red)':''}"></i></div><p>${esc(s.explanation)}</p><div class="card-footer"><span>${esc(s.period)} · ${esc(s.quality_status)}</span><button class="audit-button" data-run="${esc(s.run_id)}">Visa audit →</button></div></article>`}

function renderDomains(domains){const synthesis=domains.find(d=>d.id==="synthesis")?.latest;const cards=domains.filter(d=>d.id!=="synthesis");cards.forEach(d=>domainData[d.id]=d);const hasData=cards.some(d=>d.latest);document.getElementById("empty-state").classList.toggle("hidden",hasData);document.getElementById("dashboard-content").classList.toggle("hidden",!hasData);if(!hasData)return;
 document.getElementById("domain-cards").innerHTML=cards.map(domainCard).join("");document.querySelectorAll(".audit-button").forEach(button=>button.addEventListener("click",()=>loadAudit(button.dataset.run)));
 renderSynthesis(synthesis)
}
function renderSynthesis(synthesis){if(!synthesis)return;document.getElementById("synthesis-title").textContent=stateLabels[synthesis.state]||synthesis.state;document.getElementById("synthesis-quality").textContent=synthesis.quality_status;document.getElementById("synthesis-explanation").textContent=synthesis.explanation;document.getElementById("risk-target").textContent=synthesis.policy_target==null?"—":`${synthesis.policy_target} %`;document.getElementById("risk-meter").style.width=`${synthesis.policy_target||0}%`;document.getElementById("synthesis-score").textContent=number(synthesis.score);document.getElementById("global-asof").textContent=formatDate(synthesis.as_of);document.getElementById("synthesis-audit").onclick=()=>loadAudit(synthesis.run_id);const lag=(synthesis.synthesis_contributions||[]).filter(x=>x.stale||x.dropped).map(x=>`${x.domain}: ${x.period||"saknas"}${x.dropped?" (bortfallen)":" (föråldrad)"}`);document.getElementById("synthesis-lag").textContent=lag.length?lag.join(" · "):"Alla domäner inom förväntad publiceringslagg"}
function renderHistory(rows){const ordered=[...rows].reverse();const chart=document.getElementById("history-chart");chart.innerHTML=ordered.map(row=>{const height=Math.max(3,Math.min(48,Math.abs(row.score||0)/1.5*48));return `<div tabindex="0" class="bar ${esc(row.state)} ${row.score<0?'negative':''}" style="height:${height}%"><span>${esc(row.period)} · ${stateLabels[row.state]} · ${number(row.score)}</span></div>`}).join("");document.getElementById("history-table").textContent=ordered.map(r=>`${r.period}: ${stateLabels[r.state]}, score ${number(r.score)}`).join("; ")}
async function renderCompare(){const domains=["sweden","usa","global","synthesis"];const all=await Promise.all(domains.map(d=>api(`/api/v1/domains/${d}/signals?limit=12`)));const periods=[...new Set(all.flat().map(r=>r.period))].sort().reverse().slice(0,12);document.getElementById("compare-head").innerHTML=`<tr><th>Domän</th>${periods.map(p=>`<th>${p}</th>`).join("")}</tr>`;document.getElementById("compare-body").innerHTML=domains.map((d,i)=>`<tr><th>${d==="sweden"?"Sverige":d==="global"?"Globalt":d==="synthesis"?"Syntes":"USA"}</th>${periods.map(p=>{const row=all[i].find(r=>r.period===p);return `<td><span class="state ${row?.state||''}">${row?stateLabels[row.state]:"—"}</span></td>`}).join("")}</tr>`).join("")}
async function loadAudit(runId){const audit=await api(`/api/v1/signals/${runId}/audit`);const fields=[["Körnings-ID",audit.run_id],["Signal­motor",audit.engine_version],["Datavintage / as-of (UTC)",audit.as_of],["Datamode",audit.data_mode],["Profil",`${audit.profile_id} ${audit.profile_version}`],["Kandidat",audit.candidate_state],["Slutligt tillstånd",audit.state],["Bekräftelser",audit.confirmation_count],["Kvalitet",audit.quality_status],["Policyversion",`${audit.policy.id} ${audit.policy.version}`]];const series=audit.component_contributions||[];const domains=audit.synthesis_contributions||[];const components=series.length?series.map(c=>`<div class="component-row"><b>${esc(c.label)}</b><span>score ${number(c.indicator_score)}</span><span>vikt ${number(c.effective_weight)}</span><span>bidrag ${number(c.contribution)}</span></div>`).join(""):domains.map(c=>`<div class="component-row"><b>${esc(c.domain)} · ${esc(c.period||"saknas")}</b><span>${c.dropped?"bortfallen":c.stale?"föråldrad":"aktuell"} · ${c.age_months??"—"} mån</span><span>vikt ${number(c.weight_effective)}</span><span>bidrag ${number(c.contribution)}</span></div>`).join("");document.getElementById("audit-content").innerHTML=`<dl>${fields.map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join("")}</dl><h3>Komponentbidrag</h3><div class="component-list">${components||"<p>Inga bidrag tillgängliga.</p>"}</div>`;showView("quality")}
async function renderAlerts(){const [signalAlerts,qualityIssues]=await Promise.all([api("/api/v1/alerts"),api("/api/v1/quality/issues")]);const qualityAlerts=qualityIssues.filter(issue=>issue.status==="OPEN").map(issue=>({level:issue.severity,event_type:"DATA_QUALITY",message:issue.message,created_at:issue.opened_at}));const alerts=[...signalAlerts,...qualityAlerts].sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)));document.getElementById("alert-count").textContent=alerts.length;document.getElementById("alerts-list").innerHTML=alerts.length?alerts.slice(0,20).map(a=>`<div class="alert"><b>${esc(a.level)} · ${esc(a.event_type)}</b><span>${esc(a.message)}</span><span>${formatDate(a.created_at)}</span></div>`).join(""):"<p>Inga larm.</p>"}
async function renderTda(){const [tda,universe]=await Promise.all([api("/api/v1/tda/latest"),api("/api/v1/tda/universe")]);const el=document.getElementById("tda-content");if(!tda){el.innerHTML=`<div class="empty-state"><h2>Ingen TDA-körning ännu</h2><p>Universum ${esc(universe.version_id)} är låst och produktägargodkänt.</p></div>`;return}const isDemo=tda.quality_status==="DEMO";const isResearch=tda.quality_status==="RESEARCH";document.getElementById("tda-nav-status").textContent=isDemo?"Demo":isResearch?"Research":tda.quality_status;const hasStress=tda.stress_score!=null;const artifact=tda.artifact;el.innerHTML=`<section class="stress-card"><div class="label-row"><p class="eyebrow">Topologiskt stressindex</p><span class="tda-status ${isDemo?'demo':isResearch?'research':''}">${esc(tda.quality_status)}</span></div><div class="stress-value ${hasStress?"":"uncalibrated"}">${hasStress?number(tda.stress_score,1):"Ingen stressnivå ännu"}</div>${hasStress?`<div class="stress-track"><i style="left:${Math.max(0,Math.min(100,tda.stress_score))}%"></i></div>`:""}<p><span class="state NEUTRAL">${esc(tda.novelty_status)}</span> · riktning ${esc(tda.direction)}</p>${!hasStress?'<p class="calibration-note"><b>Ej kalibrerat</b> betyder att features är verkligt beräknade, men att ingen validerad regel ännu översätter dem till stressnivå, riktning eller sannolikhet. Det är ett avsiktligt säkerhetslås — inte ett datafel.</p>':""}${isDemo?'<p class="demo-disclaimer">Detta är ett syntetiskt visningsexempel, inte ett uppmätt modellresultat.</p>':isResearch?'<p class="research-disclaimer">Diagrammen och sammanfattningarna är verkligt beräknade. Stressnivå och riktning visas först efter förregistrerad kalibrering.</p>':""}<p class="warning-list">${tda.warnings.map(w=>`• ${esc(w)}`).join("<br>")}</p>${artifact?`<div class="tda-provenance"><b>Verifierbar körning</b><span>${esc(artifact.input_start)}–${esc(artifact.input_end)} · ${artifact.row_count} handelsdagar</span><span>${esc(artifact.backend)} ${esc(artifact.backend_version)}</span><code title="${esc(artifact.input_sha256)}">input ${esc(artifact.input_sha256.slice(0,16))}…</code></div>`:""}</section><section class="feature-card"><p class="eyebrow">Beräknade sammanfattningar</p><h2>${esc(tda.feature_version)}</h2><dl>${Object.entries(tda.features).map(([key,value])=>`<dt>${esc(tdaFeatureLabels[key]||key.replaceAll('_',' '))}</dt><dd>${number(value)}</dd>`).join("")}</dl><p class="warning-list">${tda.window_days} handelsdagars fönster · universum ${esc(tda.universe_version)} · ${esc(universe.status)}</p></section>`}
async function init(){try{const [domains,history]=await Promise.all([api("/api/v1/domains"),api("/api/v1/domains/synthesis/signals?limit=24")]);renderDomains(domains);renderHistory(history);await Promise.all([renderCompare(),renderAlerts(),renderTda()]);const hash=location.hash.slice(1);if(["overview","compare","quality","tda"].includes(hash))showView(hash)}catch(error){document.getElementById("empty-state").classList.remove("hidden");document.getElementById("empty-state").querySelector("p").textContent=`Dashboarden kunde inte laddas: ${error.message}`;document.getElementById("dashboard-content").classList.add("hidden")}}
init();
